version: "3.7"
services:
  web:
    build:
      args:
        user: 'sunday'
        uid: 1000
        TZ: America\New_York
      context: ./
      dockerfile: Dockerfile
    image: sunday
    container_name: sunday-app
    restart: unless-stopped
    volumes:
      - ./docker-compose/web/timezone:/etc/timezone
      - ./docker-compose/web/cron/scheduler-cron:/etc/cron.d/scheduler-cron
      - sunday_db:/var/lib/mysql
    networks:
      - sunday
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    container_name: sunday-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
      - sunday_db:/var/lib/mysql
      - ./docker-compose/mysql:/home/root/cache/
    networks:
      - sunday
  nginx:
    image: nginx:alpine
    container_name: sunday-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx/vhosts:/etc/nginx/conf.d/
    networks:
      - sunday
  redis:
    image: 'redis:alpine'
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - ./docker-compose/redis:/data
    networks:
      - sunday
  # memcached:
  #     image: 'memcached:alpine'
  #     ports:
  #         - '11211:11211'
  #     networks:
  #         - sail
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - sunday
  cron:
    build:
      context: .
      dockerfile: cron.dockerfile
    container_name: cron
    volumes:
      - ./:/var/www
    networks:
      - sunday
networks:
  sunday:
    driver: bridge
volumes:
  sunday_db:
    driver: local
